spring.application.name=social
# koneksi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/social
spring.datasource.username=postgres
spring.datasource.password=postgres

# pembuatan tabel
spring.jpa.hibernate.ddl-auto=update

spring.session.jdbc.initialize-schema=always