server.port=8080

spring.application.name=social
# koneksi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/social
spring.datasource.username=postgres
spring.datasource.password=postgres

# pembuatan tabel
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.session.jdbc.initialize-schema=always

# JWT
#JWT
app.jwt.secret=${JWT_SECRET:NpoiASND87zx998qy982384NnvdhknNosS020394lfiddfyooPoyyfdg189234umivNnduoeiIUEOWosLSlSMIOIQuynIUSNYDf623nUNSUDYF00IUNDYFnj}

#JWT 24 hours in milliseconds
app.jwt.expiration=86400000 

springdoc.packagesToScan=id.co.bpddiy.social
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
